server:
  port: 8080

spring:
  application:
    name: Deer-Flow

  ai:
    #    dashscope:
    #      api-key: ${DASHSCOPE_API_KEY}
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max
    tavily:
      api-key: ${TAVILY_API_KEY}
      max-results: 3
      include-raw-content: true
      include-images: true
      include-image-descriptions: true


logging:
  level:
    com.alibaba.cloud.ai.example.graph: debug