server:
  port: 8096

spring:
  application:
    name: Deer-Flow

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
    tavily:
      api-key: ${TAVILY_API_KEY}
      max-results: 3
      include-raw-content: true
      include-images: true
      include-image-descriptions: true
    mcp:
      client:
        sse:
          servers-configuration: classpath:mcp-servers.json
        stdio:
          servers-configuration: classpath:mcp-servers.json
        toolcallback:
          enabled: true


